stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

autobuild:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:autobuild -f ./autobuild/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:autobuild
  only:
    - master

autobuild-vips:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/vips:autobuild -f ./autobuild-vips/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/vips:autobuild
  only:
    - master

nobuild:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:nobuild -f ./nobuild/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:nobuild
  only:
    - master

nobuild-vips:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/vips:nobuild -f ./vips-nobuild/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/vips:nobuild
  only:
    - master
