dist: trusty
sudo: required

script:
  - npm i -g travis-env && eval "$(travis-env)"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . -t eventology/alpine-node:latest
  - docker push eventology/alpine-node:latest
