dist: trusty
sudo: required

script:
  - npm install -g travis-env && source travis-env
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . -t eventology/alpine-node:latest
  - docker push eventology/alpine-node:latest
